name: Deploy Docs to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'package.json'
      - 'docusaurus.config.js'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Setup Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Install dependencies
        working-directory: ./docs  # 指定工作目录
        run: yarn install
        
      - name: Build
        working-directory: ./docs  # 指定工作目录
        run: |
          yarn build
          echo "验证构建目录:"
          ls -la build/ || echo "构建失败，目录未生成"
          [ -d "build" ] && echo "构建成功" || (echo "构建失败"; exit 1)
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./docs/build  # 更新发布目录路径
          publish_branch: gh-pages
          force_orphan: true
          full_commit_message: "Deploy Docusaurus site $(date -u +'%Y-%m-%d %H:%M:%S')"