name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          clean: true  # 确保初始检出是干净的
          
      - name: Clean workspace
        run: |
          git clean -ffdx  # 强制删除所有未跟踪文件
          git reset --hard  # 重置所有更改
          
      - name: Setup Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile  # 使用固定lockfile
        
      - name: Build
        run: yarn build  # 直接运行build，跳过version patch

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./build
          force_orphan: true
          keep_files: false
